### ISSUE TITLE
Implement Tutor Action Buttons

### ISSUE THREAD

**Issue by skydev2020** [skydev2020/learnon3#116]
Implement these features.
![image](https://user-images.githubusercontent.com/57546027/79640070-9631a900-815d-11ea-9af1-99f067fc7aa2.png)

**Comment by skydev2020** [comment]
Align buttons to right align.
![image](https://user-images.githubusercontent.com/57546027/79640831-ce3aeb00-8161-11ea-81aa-c64b630951da.png)

**Comment by softActor531** [comment]
Implemented Tutor Action buttons.
