### ISSUE TITLE
System Users

### ISSUE THREAD

**Issue by skydev2020** [skydev2020/learnon3#120]
![image](https://user-images.githubusercontent.com/57546027/79641001-e19a8600-8162-11ea-99e5-844b19ff4e44.png)
![image](https://user-images.githubusercontent.com/57546027/79641013-f0813880-8162-11ea-8bb6-d4c3af7d6e4e.png)

**Comment by skydev2020** [comment]
And when delete show confirmation dialog.
Applies to all List Page

**Comment by skydev2020** [comment]
And how to add a user?

**Comment by skydev2020** [comment]
And same style as Tutor List

**Comment by softActor531** [comment]
Updated Admin/System Users.
