### ISSUE TITLE
Remove 'User Management' submenu under logout

### ISSUE THREAD

**Issue by skydev2020** [skydev2020/learnon3#97]
1. Remove 'User Management' under logout
2. Remove prefilled password under my profile under 'My profie'
3. Properly align 'Save' and 'Cancel' button

![image](https://user-images.githubusercontent.com/57546027/79178862-5755c900-7dd4-11ea-8274-f7eca1f00ac6.png)

![image](https://user-images.githubusercontent.com/57546027/79178942-89672b00-7dd4-11ea-863c-f501f4845c49.png)

**Comment by softActor531** [comment]
Remove submenu & complete My profile menu
